export  default{
    showHeader:({commit})=>{
        commit("showHeader")
    },
    hideHeader:({commit})=>{
        commit("hideHeader")
    },
    hideFooter:({commit})=>{
        commit("hideFooter")
    },
    showFooter:({commit})=>{
        commit("showFooter")
    },
    showLoading:({commit})=>{
        commit("showLoading")
    },
    hideLoading:({commit})=>{
        commit("hideLoading")
    }
}